### ISSUE TITLE
Arrow Head Size

### ISSUE THREAD

**Issue by qsek** [ggarra13/mrv2#202] opened 2024-03-09 15:05 UTC
If its not too much work, i think a size option for the arrow head would be useful.
If you annotate with arrows with pen size 2 in a zoomed in view, often the arrow head lines are too big in proportion to the length.
If you want to get really fancy, an additional "auto" option would be amazing where the arrow head scales with the line length.
Also for zoomed in view, it would be helpful to have pen sizes below 2.
![2024-03-09_16-05-15](https://github.com/ggarra13/mrv2/assets/1266293/d7520e7a-b8a6-4ec6-ab02-684e996f4fc1)

**Comment by ggarra13** [comment] 2024-03-10 11:51
Please try v1.0.9 that allows pixel size of 1 and arrow heads automatically calculated from the arrow length:

http://www.sourceforge.net/projects/mrv2/files/beta

**Comment by qsek** [comment] 2024-03-10 17:07
The arrow head feature is awesome. Thanks for that!
But i had no luck with the pen size. The width of any drawing tool stays the same as setting 2.
So changing it to 1 (and even 0) produces the same width as 2.

**Comment by qsek** [comment] 2024-03-10 17:15
And i think i've found a bug that happens with saving and loading the session with these new annotation changes.
SAving is without error, but when i load the session again, the log says:
`ERROR: [mrv2s] Invalid OCIO Ics ''.`

**Comment by ggarra13** [comment] 2024-03-10 17:59
> And i think i've found a bug that happens with saving and loading the session with these new annotation changes.
> SAving is without error, but when i load the session again, the log says:
> `ERROR: [mrv2s] Invalid OCIO Ics ''.`
> And no annotations are loded.

It is a bug with the new Input Color Space flag kept on each image.  I'll have a fix later.

**Comment by ggarra13** [comment] 2024-03-10 20:28
Both the 1 pixel cursor and the broken Session loading should be fixed in the latest beta in sourceforge.  Give it a try and report back.

**Comment by qsek** [comment] 2024-03-11 19:31
Broken session loading is fixed. 👍 
Still no luck with Pen Size 1.
![2024-03-11_20-24-17](https://github.com/ggarra13/mrv2/assets/1266293/310e5c46-2f6e-4f40-96a0-0d3f37be28dc)

Another bug with the rotate function is the placement of text. After you created the text and clicked on another tool (i have not yet discovered a different way of confirming the text input), the text will be set in a different place than you entered it.
I've also not discovered how to move already placed annotations.

**Comment by ggarra13** [comment] 2024-03-11 19:47
> Still no luck with Pen Size 1.

You may need to tell me OS, what resolution, what tool and if using soft or hard pencil, as it works for me.  Here's a zoom view with an arrow of one pixel.
![Screenshot from 2024-03-11 16-44-20](https://github.com/ggarra13/mrv2/assets/6072843/362e080d-378d-4f30-9c70-b8078052e2af)

**Comment by ggarra13** [comment] 2024-03-11 19:51
> After you created the text and clicked on another tool (i have not yet discovered a different way of confirming the text input).

You can click on another tool or click on the green X next in the corner of box input.  You can hit Esc or delete all text and hit the now red X in the cordner.

> the text will be set in a different place than you entered it.

That's a feature, not a bug.  You can, at a later time, reposition the text by using the RMB on the text tool.  A requester will show allowing you to select which text you want to edit and if you click ok, you will be back at the editing mode of the text to change its contents.

**Comment by ggarra13** [comment] 2024-03-11 19:55
> I've also not discovered how to move already placed annotations.

That currently cannot be done.  It's not like we have Photoshop with layers!  Albeit the data is stored, so I may add that feature at a later time (the UI aspect of it is tricky -- like show the annotation with a bounding box and then use some hotkey to go to the next or previous annotation.  The problem is with Erased annotation, where you would not see anything).

**Comment by ggarra13** [comment] 2024-03-11 21:48
> After you created the text and clicked on another tool (i have not yet discovered a different way of confirming the text input).

I am compiling a version now where text input can be confirmed by pressing SHIFT + Enter.  It should be in sourceforge beta in an hour if you are on Windows, in a couple of hours if you are on Linux or macOS.

**Comment by qsek** [comment] 2024-03-11 23:36
Now this looks way better. Finer on Pen Size 1 and i even can enter Pen Size 0 to go a bit finer still. Im super happy. Thanks 👍 
(btw im on Win10, 1440p)

**Comment by qsek** [comment] 2024-03-11 23:45
> >    the text will be set in a different place than you entered it.

> That's a feature, not a bug. You can, at a later time, reposition the text by using the RMB on the text tool.

I meant that in the rotated view the text gets teleported to a different position after you confirmed it. Here is a recording:
![mrv2_2024-03-12_00-40-00](https://github.com/ggarra13/mrv2/assets/1266293/ebe872a9-312b-4f12-ad1b-725b925cd2e2)
(this is with the newest version)

**Comment by ggarra13** [comment] 2024-03-12 00:19
New betas fixing the text problem:

.exe:
https://mega.nz/file/vW5ViQJK#jGkzUAmjyoFB__Skt6ymtgM9EGJq1T1K3AW_wztFA9E

.zip:
https://mega.nz/file/vPRSFZqA#I3yv0I7ZGn4KkBSw-0ZHCPeDrBDPyA39qOfQFwWxR2s

**Comment by ggarra13** [comment] 2024-03-23 18:30
All fixed and addressed in v1.1.0.

**Closed by ggarra13** 2024-03-23 18:30 UTC
