### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#187] opened 2024-02-12 10:23 UTC
When trying to do a clean build (./runme.sh clean) building fails.

```
[160/312] Performing download step (git clone) for 'Freetype'
Cloning into 'Freetype'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 7754 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'Freetype'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 8081 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'Freetype'...
-- Had to git clone more than once: 3 times.
```
or dozens of

`./fltk14/fltk_wrap.cpp:176860:13: error: invalid use of incomplete type ‘class Fl_PostScript_Graphics_Driver’`

All dependencies are installed and updated.

**Comment by ggarra13** [comment] 2024-02-12 16:15
For your first error, your network is failing (ie. git clone is not able to access the curl repository).  There have been intermittent errors since yesterday.

For your second error, there's an inconsistency between pyFLTK and FLTK and cmake seems not to be smart enough to detect the change.   You many need to clean the dir and start the build from scratch.

Try running:

```
git pull
./runme.sh clean
```

**Comment by ggarra13** [comment] 2024-02-12 16:22
Also, note that the build now requires "meson" to be installed.

**Comment by ggarra13** [comment] 2024-02-12 16:37
BTW:  
You can see the latest build status at the top of the main page.  It says: "Full Builds: passing".  That status is from yesterday.

You can further verify the build is working in the Actions tab.  I just started a new build both locally (on Rocky Linux 8.9) and remotely (on Ubuntu 20.04) to verify all is working, just in case.  So far, everything is working.

**Comment by ggarra13** [comment] 2024-02-12 17:34
Both the Rocky Linux 8.9 build finished successfully (I had to do` ./runme.sh `twice as I also got the network error).
And the Ubuntu 20.04 remotely also finished successfully.

**Comment by SteffenDuenner** [comment] 2024-02-13 08:21
OK, thanks for your efforts. I'll give it another shot today and report back.

**Comment by ggarra13** [comment] 2024-02-13 12:19
What's your swig version and Linux distro and version?

I can verify these versions work:

```
swig -version

SWIG Version 4.0.2
```

```
swig -version

SWIG Version 4.2.0
```
I think you may have either too old or too new swig version.

**Comment by ggarra13** [comment] 2024-02-13 12:21
If you don't care about pyFLTK, you can disable it from the build with:

./runme.sh -D MRV2_PYFLTK=OFF

It is only used for the plug-in that allows you to update mrv2 from the menus (you might want to then move BUILD-Linux-amd64/Release/install/python/plug-ins/update-mrv2.py to another directory).

**Comment by SteffenDuenner** [comment] 2024-02-13 12:21
Mine is

```
SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

```
And my OS is Linux Mint 21.3 x86_64

**Comment by ggarra13** [comment] 2024-02-13 12:40
Still, I am puzzled, so I am going to bother you a bit more, if you don't mind.

Can you verify that:

`git log `

reports:

commit 15d1a00c598373a8f8fd30c955ee4da266aef70c (origin/main, origin/HEAD)

**Comment by SteffenDuenner** [comment] 2024-02-13 12:46
You're **very welcome** to bother me ;)

`git log`

gives me

```
commit 8cc996dc8fc7885ce135474800020b8143e69922 (HEAD -> main, origin/main, origin/beta, origin/HEAD)
Author: Gonzalo Garramuño <ggarra13@gmail.com>
Date:   Tue Feb 13 04:10:23 2024 -0300

    Added check for extension (format) for VP9 and AV1 codecs.

```

**Comment by ggarra13** [comment] 2024-02-13 12:54
Ok.  You are a tad behind some changes I did to pyFLTK.  It should not have changed anything, but maybe I had screwed up...

```
git pull
./runme.sh   
```

Don't clean the dir, it won't do anything to your already compiled mrv2 as pyFLTK is independent (well, it needs Python and FLTK, but you already compiled those, so it should be a relatively fast compile if it works).

**Comment by ggarra13** [comment] 2024-02-13 12:59
Oh da**!  I know what happened.  I forgot to merge my "beta" branch into the "main" branch.  Try:

```
git pull
./runme.sh   
```
and I swear it will work this time around!

**Comment by SteffenDuenner** [comment] 2024-02-13 13:00
Cool! I'm giving this a shot right now. Hang on...

**Comment by ggarra13** [comment] 2024-02-13 13:04
Also, in case it fails, go to and see that it reads like this:
```

cd BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK
git log

commit a1d3bf182e6c085779b6e7e7315bf15f384f7112 (HEAD)
Author: Albrecht Schlosser <albrechts.fltk@online.de>
Date:   Wed Feb 7 20:03:29 2024 +0100

    Fix GitHub CI build and minor CMake issues
    
    - GitHub CI: fix wrong CMake option name
    - fl_add_library: disable debug output (MSVC), fix formatting
```

**Comment by SteffenDuenner** [comment] 2024-02-13 13:07
It actually still fails with the same fltk error, but it gives me exactly this

```
steffen@V16m:~/mrv2$ cd BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK
steffen@V16m:~/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK$ git log
commit a1d3bf182e6c085779b6e7e7315bf15f384f7112 (HEAD)
Author: Albrecht Schlosser <albrechts.fltk@online.de>
Date:   Wed Feb 7 20:03:29 2024 +0100

    Fix GitHub CI build and minor CMake issues
    
    - GitHub CI: fix wrong CMake option name
    - fl_add_library: disable debug output (MSVC), fix formatting

```

**Comment by ggarra13** [comment] 2024-02-13 13:10
I'll be... What does this directory give you?

```
cd BUILD-Linux-amd64/Release/pyFLTK-prefix/src/pyFLTK
svn info

Working Copy Root Path: /media/gga/datos/code/applications/mrv2/BUILD-Linux-amd64/Release/pyFLTK-prefix/src/pyFLTK
URL: https://svn.code.sf.net/p/pyfltk/code/branches/fltk1.4
Relative URL: ^/branches/fltk1.4
Repository Root: https://svn.code.sf.net/p/pyfltk/code
Repository UUID: db8d5ec9-520e-0410-b818-d5ed6a5c6bea
Revision: 627
Node Kind: directory
Schedule: normal
Last Changed Author: andreasheld
Last Changed Rev: 627
Last Changed Date: 2024-01-27 18:10:00 -0300 (sáb, 27 ene 2024)

```

**Comment by SteffenDuenner** [comment] 2024-02-13 13:11
Hmm...

`svn: E155007: '/home/steffen/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK' is not a working copy`

**Comment by ggarra13** [comment] 2024-02-13 13:12
> svn: E155007: '/home/steffen/mrv2/BUILD-Linux-amd64/Release/FLTK-prefix/src/FLTK' is not a working copy

pyFLTK *not* FLTK.

**Comment by SteffenDuenner** [comment] 2024-02-13 13:14
Ah sorry:

```
Working Copy Root Path: /home/steffen/mrv2/BUILD-Linux-amd64/Release/pyFLTK-prefix/src/pyFLTK
URL: https://svn.code.sf.net/p/pyfltk/code/branches/fltk1.4
Relative URL: ^/branches/fltk1.4
Repository Root: https://svn.code.sf.net/p/pyfltk/code
Repository UUID: db8d5ec9-520e-0410-b818-d5ed6a5c6bea
Revision: 627
Node Kind: directory
Schedule: normal
Last Changed Author: andreasheld
Last Changed Rev: 627
Last Changed Date: 2024-01-27 22:10:00 +0100 (Sa, 27 Jan 2024)
```

**Comment by ggarra13** [comment] 2024-02-13 13:20
Ok.

FLTK - same version
pyFLTK - same version
swig - same version

One more thing to check:

g++ --version

and attach your latest compile.log (the one where pyFLTK fails):

BUILD-Linux-amd64/Release/compile.log

**Comment by SteffenDuenner** [comment] 2024-02-13 13:27
Thanks for your patience (I'll have to walk the dog right now, so I'll be AFK ~1h soon):

```
steffen@V16m:~/mrv2$ g++ --version
g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and I attached the compile.log here. [compile.log](https://github.com/ggarra13/mrv2/files/14266383/compile.log)

**Comment by ggarra13** [comment] 2024-02-13 13:58
> Thanks for your patience

No... Thanks to YOUR patience!

Ok.  After asking chatgpt and poking around, it seems the problem we are facing is a new "feature" of gcc/g++ 12.  I can try one more thing.

Attach these files:

```
BUILD-Linux-amd64/Release/pyFLTK-prefix/src/pyFLTK/fltk14/fltk_wrap.cpp
BUILD-Linux-amd64/Release/pyFLTK-prefix/src/pyFLTK/fltk14/fltk_wrap.h
```

I'll try to compile them with my older compiler and see if they compile without errors.

**Comment by SteffenDuenner** [comment] 2024-02-13 16:09
So just to confirm: I can't help you with this right now and you're currently trying to compile the fixes for a newer compiler with an older compiler (gcc 11?) and see if the old version still works?

**Comment by ggarra13** [comment] 2024-02-13 16:31
No.  Never mind.  It is not a compiler issue, as I was able to check it another way.  I'm going to have you try again (this is the last one and then I give up).  Do the following:

```
rm -rf BUILD-Linux-amd64/Release/FLTK-prefix
rm -rf BUILD-Linux-amd64/Release/pyFLTK-prefix
git switch main
git pull
./runme.sh
```
I am having remove the directories in case there was something left behind that was incomplete.

**Comment by SteffenDuenner** [comment] 2024-02-14 08:23
OK, here I am again. Sorry for the late reply.
I just tried to rebuild and it still failed. I attached the compile.log (
[compile.log](https://github.com/ggarra13/mrv2/files/14276946/compile.log) ) but I don't have the pyFLTK-prefix folder / files:
![image](https://github.com/ggarra13/mrv2/assets/33224667/979c1502-a28d-43b2-9a63-4d90cd75368d)

**Comment by ggarra13** [comment] 2024-02-14 08:57
I was working on the build scripts and I screwed up the download process.  That's why you did not get any pyFLTK-prefix files.  I am done testing it now and adding more debugging info.  Try it again:

```
rm -rf BUILD-Linux-amd64/Release/pyFLTK-prefix
git switch main
git pull
./runme.sh
```

Send me the compile.log if it still does not work.

**Comment by SteffenDuenner** [comment] 2024-02-14 11:14
OK, I rebuilt the latest main, it still fails but at least I have some files in the pyFLTK-prefix folder.
Here's the [compile.log](https://github.com/ggarra13/mrv2/files/14278667/compile.log)

And the 3 files from the pyFLTK-prefix folder: 
[fltk14.zip](https://github.com/ggarra13/mrv2/files/14278705/fltk14.zip)

**Comment by ggarra13** [comment] 2024-02-14 18:49
> OK, I rebuilt the latest main, it still fails but at least I have some files in the pyFLTK-prefix folder. Here's the [compile.log](https://github.com/ggarra13/mrv2/files/14278667/compile.log)
> 
> And the 3 files from the pyFLTK-prefix folder: [fltk14.zip](https://github.com/ggarra13/mrv2/files/14278705/fltk14.zip)

Thanks for your patience.  Try it again, I think the issue is that you have an older version of FLTK installed in /usr/include and that's causing the conflict.  The swig script was re-arranging the paths in the wrong order and putting /usr/include before the include/ in the build location.

```
cd mrv2
git switch main
git pull
./runme.sh
```

**Comment by SteffenDuenner** [comment] 2024-02-14 19:16
Great! I just compiled from scratch and all is shiny again.
Thanks a lot!

**Comment by ggarra13** [comment] 2024-02-14 21:46
> Great! I just compiled from scratch and all is shiny again.
> Thanks a lot!

Most excellent!!! It was a tricky one to fix.  I am closing the issue now.

**Closed by ggarra13** 2024-02-14 21:46 UTC
