### ISSUE TITLE
does not remember

### ISSUE THREAD

**Issue by Azik099** [ggarra13/mrv2#105] opened 2023-09-14 06:25 UTC
I disabled the logs panel but for some reason it doesn’t remember and it will show me again. please fix that

**Comment by ggarra13** [comment] 2023-09-14 09:57
Do you mean you closed it and exited mrv2 and still shows up (without any error triggering it)?

Or:

You went to Preferences->Errors and set it to Do Nothing (and still shows up with an error triggering it)?

**Comment by Azik099** [comment] 2023-09-14 11:50
Yes, the panel does not close, I disabled it in the parameters but it appears again and again, please check it yourself

I think you understand me

**Comment by Azik099** [comment] 2023-09-14 11:51
I'll rollback previous versions for now

**Comment by ggarra13** [comment] 2023-09-14 12:32
I'll need more information (be clear, please), as I cannot reproduce it.  Please answer each of these questions:

1) First, what OS are you on?  
2) You set Preferences->Errors->Do Nothing, is that right?
3) Your Log is on a panel or on a floating window?
4) You closed the Log Panel/Window and then exited mrv2 cleanly by closing the main window or pressing Esc.
5) The Log Panel/Window appears even when there is no error?

**Comment by Azik099** [comment] 2023-09-14 12:38
i mean it
my oc is windows 11

**Comment by Azik099** [comment] 2023-09-14 12:39
You set Preferences->Errors->Do Nothing, is that right? - yes i do the same

**Comment by ggarra13** [comment] 2023-09-14 12:43
Ah.  Okay, you are getting the Hotkey corruption issue which was reported earlier by someone else.  

Please delete this file from your disk (reported in the Log Window):

C:\Users\turdi\.filmaura\mrv2.keys.prefs

That should fix the issue.

**Comment by Azik099** [comment] 2023-09-14 13:01
its helped me thank you so much.
I  think such problems will not arise again

**Closed** 2023-09-15 21:08 UTC
