### ISSUE TITLE
Mrv2 clamps the image after using OCIO

### ISSUE THREAD

**Issue by archct** [ggarra13/mrv2#288] opened 2024-08-20 16:55 UTC
After applying any Aces config in the OCIO settings, the image values begin to be clamped using rgb channels. The values are truncated to 1, however, if we look through the nuke viewer, we see that the shooting values from the Arri camera, when interpreted through the Arri Wide Gamut (EI800), are much higher than one.

This results in loss of information when changing the gamma and exposure parameters. It is necessary to ensure that the image in mrv2 corresponds in values to the image from the nuke viewer. How to achieve this, it would be useful to get instructions on how to properly configure Access in mrv2. 
A similar problem is observed in mrv

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint Kernel 5.4.0
 - Version mrv2 v1.2.3 (the same problem on mrv 6.2.3)
![mrv2](https://github.com/user-attachments/assets/f0665477-889c-4764-b240-bead864fc119)
![nuke_viewer](https://github.com/user-attachments/assets/9eeabc13-72d1-4da6-b94f-de8077b77009)

**Comment by ggarra13** [comment] 2024-08-20 17:15
Things to check in mrv2:

- Preferences->Video->Color Buffers' Accuracy set to Automatic or Full Float.

If that's not it, then I will need a sample .exr file to check the problem myself.

**Comment by ggarra13** [comment] 2024-08-21 09:56
Thanks for the .exr.  I am going to need also the .ocio config you are using and all the OCIO settings you use.

**Comment by archct** [comment] 2024-08-21 12:06
https://drive.google.com/file/d/1ukGMh7MneQK9ljnd9BMH_yPloHkSNcIm/view?usp=sharing

I uploaded the exr and config file to the disk, which is in the settings.
The configs in this case are slightly different, but when using 1.0.3 in mrv2, the colors are also displayed incorrectly, so the reason is probably not in different configs.

![mrv2](https://github.com/user-attachments/assets/74b5e411-808e-4ac9-94ea-60d2cc063169)

![mrv3](https://github.com/user-attachments/assets/2fa9d11d-b583-4c49-acd6-ad2ad104b1b4)


![mrv1](https://github.com/user-attachments/assets/9d56e256-ab1c-45e7-82c3-3c6bf68e0058)

![mrv5](https://github.com/user-attachments/assets/9b922a75-50bd-4aa7-a2b8-dc21f3efe2da)

**Comment by ggarra13** [comment] 2024-08-21 12:14
Thanks.  I was able to reproduce the problem on mrv2 *AND* OpenRV with the old aces_1.0.3.  

The issue seems to be that aces_1.0.3 is a v1.0 config that has been deprecated.  

You should not confuse ACES 1.0.3 with ACES 1.3 which is the latest one, btw.

I'm afraid I don't have a solution or an idea what the problem might be.  At first glance it seems it could be an incompatibility in OCIO 2, that somehow Nuke works around it.

**Comment by archct** [comment] 2024-08-21 12:59
I came to the conclusion that mrv2 truncates values for some reason, regardless of the versioning of OCIO and config.
At the same time, even when using the latest versions of config inside nuke, we see a larger dynamic range of values, which, with a strong change in the image in gamma and gain, tries to preserve the color gradient.

**Comment by ggarra13** [comment] 2024-08-23 10:30
Fixed in v1.2.4 currently in beta.

**Closed by ggarra13** 2024-08-23 10:30 UTC
Labels: bug
